sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - g++-5
            - clang-3.8
      env:
        - CXXCOMPILER=clang++-3.8 CCOMPILER=clang-3.8

before_install:
  - sudo apt-get update -qq
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER -DCMAKE_BUILD_TYPE=Release .. && make
  - cd tests
  - ctest
